/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Zakat;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dafa Zakhulhaq
 */
public class Beranda extends javax.swing.JFrame {

        int nol_jam ;
    int nol_menit ;
    int nol_detik ;
        String kolom[] = {"Total Uang","Total Beras"} ;
        DefaultTableModel dtm = new DefaultTableModel(null, kolom) ;
    
        String kolom1[] = {"Total Uang"} ;
        DefaultTableModel dtm1 = new DefaultTableModel(null, kolom1) ;
    
    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        selectdata() ;
        selectdatamal() ;
        SetJam() ;
        SetTanggal() ;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdata2 = new javax.swing.JTable();
        tgl = new javax.swing.JLabel();
        jm = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        tgl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Zakat Fitrah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 220, 300, 130);

        jButton3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 51));
        jButton3.setText("Zakat Mal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 220, 300, 130);

        tbdata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbdata2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 300, 50);

        tgl.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tgl.setForeground(new java.awt.Color(0, 153, 51));
        tgl.setText("Tanggal");
        jPanel1.add(tgl);
        tgl.setBounds(530, 10, 80, 40);

        jm.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jm.setForeground(new java.awt.Color(0, 153, 51));
        jm.setText("Jam");
        jPanel1.add(jm);
        jm.setBounds(530, 40, 130, 40);

        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbdata);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(330, 160, 300, 50);

        tgl1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        tgl1.setForeground(new java.awt.Color(0, 153, 51));
        tgl1.setText("BERANDA");
        jPanel1.add(tgl1);
        tgl1.setBounds(250, 20, 220, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 380);

        setBounds(0, 0, 672, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Fitrah().show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Mal().show();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

        private void selectdata() {
    
        String SQL = "Select sum(uang) as total_uang, sum(beras) as total_beras  From tb_fitrah ; " ;
        ResultSet rs = KoneksiDB.executeQuery(SQL) ;
        
         dtm.getDataVector().removeAllElements();      
        try {
            
            while(rs.next()){
                String uang = "Rp. " + rs.getString(1)  ;
                String beras = rs.getString(2)+ " Kg " ;
                String data[] = {uang,beras} ;
                dtm.addRow(data);
            }
            
        }catch(SQLException ex){
            
            Logger.getLogger(Fitrah.class.getName()).log(Level.SEVERE, null, ex) ;
        }
        tbdata.setModel(dtm);
        
    }
                private void selectdatamal() {
    
        String SQL = "Select sum(harga) as total_uang  From tb_mal ; " ;
        ResultSet rs = KoneksiDB.executeQuery(SQL) ;
        
         dtm1.getDataVector().removeAllElements();      
        try {
            
            while(rs.next()){
                String harga = "Rp. " + rs.getString(1)  ;
                String data[] = {harga} ;
                dtm1.addRow(data);
            }
            
        }catch(SQLException ex){
            
            Logger.getLogger(Fitrah.class.getName()).log(Level.SEVERE, null, ex) ;
        }
        tbdata2.setModel(dtm1);
        
    }

            public void SetTanggal(){
        java.util.Date skrg = new java.util.Date() ;
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy") ;
        tgl.setText(kal.format(skrg));
    }
    public void SetJam() {
        ActionListener taskPerformer = new ActionListener() {
          @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date() ;
                int nilai_jam = dt.getHours() ;
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                String jam = Integer.toString(nilai_jam) ;                
                String menit = Integer.toString(nilai_menit) ;
                String detik = Integer.toString(nilai_detik) ;
                jm.setText("Jam "+jam+" : "+ menit+" : "+detik);
                
                
            }
            
        };
        
            new Timer(100, taskPerformer).start() ;
            
    }
    


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jm;
    private javax.swing.JTable tbdata;
    private javax.swing.JTable tbdata2;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tgl1;
    // End of variables declaration//GEN-END:variables
}
