/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Zakat;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author Dafa Zakhulhaq
 */
public class Mal extends javax.swing.JFrame {

    int nol_jam ;
    int nol_menit ;
    int nol_detik ;
    DecimalFormat df2 = new DecimalFormat(".##") ;
    
        String kolom[] = {"id_mal","nama","daftar barang","harga","tanggal","alamat"} ;
        DefaultTableModel dtm = new DefaultTableModel(null, kolom) ;
    /**
     * Creates new form frmMain
     */
    public Mal() {
        initComponents();
        
        SetJam() ;
        SetTanggal() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jm = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        tgl1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        emastv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tanitv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        namatvmal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        galiantv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        temuantv = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        namatv5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        ternaktv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        perak = new javax.swing.JRadioButton();
        emas = new javax.swing.JRadioButton();
        kambing = new javax.swing.JRadioButton();
        sapi = new javax.swing.JRadioButton();
        uang = new javax.swing.JRadioButton();
        alami = new javax.swing.JRadioButton();
        tenaga = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        totaltv = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        seacrh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamattv1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        daftarbarangtv = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setLayout(null);

        jm.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jm.setForeground(new java.awt.Color(255, 255, 255));
        jm.setText("Jam");
        jPanel1.add(jm);
        jm.setBounds(1070, 30, 130, 40);

        tgl.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText("Tanggal");
        jPanel1.add(tgl);
        tgl.setBounds(1070, 0, 80, 40);

        tgl1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        tgl1.setForeground(new java.awt.Color(255, 255, 255));
        tgl1.setText("Zakat Mal");
        jPanel1.add(tgl1);
        tgl1.setBounds(430, -10, 210, 80);

        jButton7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 51));
        jButton7.setText("Kembali");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 10, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 80);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zakat Mal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        emastv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emastvActionPerformed(evt);
            }
        });
        jPanel2.add(emastv);
        emastv.setBounds(10, 130, 130, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(150, 130, 80, 30);

        jButton1.setText("cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 130, 80, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Emas, Perak, Uang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 130, 40);

        tanitv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanitvActionPerformed(evt);
            }
        });
        jPanel2.add(tanitv);
        tanitv.setBounds(10, 210, 130, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ziro'ah/Pertanian");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 150, 120, 40);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KG");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(150, 210, 80, 30);

        jButton2.setText("cek");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(190, 210, 80, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 80, 30);

        namatvmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatvmalActionPerformed(evt);
            }
        });
        jPanel2.add(namatvmal);
        namatvmal.setBounds(10, 40, 260, 30);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ma'adin/Barang Galian");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 240, 160, 40);

        galiantv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galiantvActionPerformed(evt);
            }
        });
        jPanel2.add(galiantv);
        galiantv.setBounds(10, 280, 130, 30);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rp");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 340, 80, 30);

        jButton3.setText("cek");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(190, 280, 80, 30);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rikaz/Temuan");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 300, 160, 40);

        temuantv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temuantvActionPerformed(evt);
            }
        });
        jPanel2.add(temuantv);
        temuantv.setBounds(50, 340, 130, 30);

        jButton4.setText("cek");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(190, 340, 80, 30);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("G");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(150, 280, 80, 30);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rp");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 340, 80, 30);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rikaz/Temuan");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 300, 160, 40);

        namatv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatv5ActionPerformed(evt);
            }
        });
        jPanel2.add(namatv5);
        namatv5.setBounds(50, 340, 130, 30);

        jButton5.setText("cek");
        jPanel2.add(jButton5);
        jButton5.setBounds(190, 340, 80, 30);

        ternaktv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ternaktvActionPerformed(evt);
            }
        });
        jPanel2.add(ternaktv);
        ternaktv.setBounds(10, 460, 40, 30);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Binatang Ternak");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 370, 160, 40);

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ekor");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(70, 460, 120, 30);

        buttonGroup2.add(perak);
        perak.setText("Perak");
        perak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perakActionPerformed(evt);
            }
        });
        jPanel2.add(perak);
        perak.setBounds(180, 100, 90, 23);

        buttonGroup2.add(emas);
        emas.setText("Emas");
        emas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emasActionPerformed(evt);
            }
        });
        jPanel2.add(emas);
        emas.setBounds(90, 100, 90, 23);

        buttonGroup4.add(kambing);
        kambing.setText("Kambing/domba");
        jPanel2.add(kambing);
        kambing.setBounds(10, 430, 130, 23);

        buttonGroup4.add(sapi);
        sapi.setText("Sapi");
        sapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapiActionPerformed(evt);
            }
        });
        jPanel2.add(sapi);
        sapi.setBounds(10, 410, 130, 23);

        buttonGroup2.add(uang);
        uang.setText("Uang");
        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });
        jPanel2.add(uang);
        uang.setBounds(10, 100, 80, 23);

        buttonGroup3.add(alami);
        alami.setText("Alami");
        alami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamiActionPerformed(evt);
            }
        });
        jPanel2.add(alami);
        alami.setBounds(10, 180, 130, 23);

        buttonGroup3.add(tenaga);
        tenaga.setText("Tenaga Manusia");
        tenaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenagaActionPerformed(evt);
            }
        });
        jPanel2.add(tenaga);
        tenaga.setBounds(140, 180, 130, 23);

        jButton8.setText("cek");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(180, 420, 80, 30);

        totaltv.setEditable(false);
        totaltv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltvActionPerformed(evt);
            }
        });
        jPanel2.add(totaltv);
        totaltv.setBounds(60, 530, 200, 50);

        jButton6.setText("Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(180, 500, 80, 30);

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("TOTAL");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(100, 490, 100, 40);

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Rp.");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 530, 50, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 280, 910);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        delete.setBackground(new java.awt.Color(0, 153, 51));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(780, 120, 100, 80);

        save.setBackground(new java.awt.Color(0, 153, 51));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(340, 120, 100, 80);

        edit.setBackground(new java.awt.Color(0, 153, 51));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);
        edit.setBounds(670, 120, 100, 80);

        refresh.setBackground(new java.awt.Color(0, 153, 51));
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(450, 120, 100, 80);

        tbdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Mal", "Nama", "Daftar Barang", "Harga", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdata);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(300, 230, 620, 290);

        clear.setBackground(new java.awt.Color(0, 153, 51));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(560, 120, 100, 80);

        print.setBackground(new java.awt.Color(0, 153, 51));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(320, 550, 110, 90);

        seacrh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seacrhKeyReleased(evt);
            }
        });
        jPanel3.add(seacrh);
        seacrh.setBounds(690, 560, 230, 60);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 51));
        jLabel21.setText("SEARCH");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(570, 570, 160, 40);

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Alamat");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(110, 10, 80, 40);

        alamattv1.setColumns(20);
        alamattv1.setRows(5);
        jScrollPane3.setViewportView(alamattv1);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 60, 220, 130);

        jLabel25.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Barang yang dizakatkan");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(50, 200, 150, 40);

        daftarbarangtv.setColumns(20);
        daftarbarangtv.setRows(5);
        jScrollPane4.setViewportView(daftarbarangtv);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(20, 240, 220, 100);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(940, 90, 260, 770);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1190, 1000);

        setBounds(0, 0, 1210, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void emastvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emastvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emastvActionPerformed

    private void tanitvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanitvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanitvActionPerformed

    private void namatvmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatvmalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatvmalActionPerformed

    private void galiantvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galiantvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_galiantvActionPerformed

    private void temuantvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temuantvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temuantvActionPerformed

    private void namatv5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatv5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatv5ActionPerformed

    private void ternaktvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ternaktvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ternaktvActionPerformed

    private void perakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perakActionPerformed

    private void emasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emasActionPerformed

    private void totaltvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
    if(emas.isSelected())
    {
        
        jLabel5.setText("G");
        String emass = emastv.getText().toString() ;
        double emast = Double.parseDouble(emass) ;
        
        if(emast < 90){
        double emash = 0 ;
        emastv.setText(emash+"");        
        }else
        {
        double emash = emast / 100 * 2.5 ;
        
        emastv.setText(emash+"");        
        }
        
    }else if(uang.isSelected())
    {
        
        jLabel5.setText("Rp");
        String uangs = emastv.getText().toString() ;
        double uangt = Double.parseDouble(uangs) ;
        
        if (uangt < 80000){
        double uangh = 0 ;
        
        emastv.setText(uangh+"");        
        }
        else{
        double uangh = uangt / 100 * 2.5 ;
        
        emastv.setText(uangh+"");        
        }
        
    }else if(perak.isSelected())
    {
        jLabel5.setText("Rp");
        String peraks = emastv.getText().toString() ;
        double perakt = Double.parseDouble(peraks) ;
     
        if(perakt < 600)
        {
            
        double perakh = 0 ;
        
        emastv.setText(perakh+"");        
        
            
        }else{
            
        double perakh = perakt / 100 * 2.5 ;
        
        emastv.setText(perakh+"");        
        
            
        }
        
        
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapiActionPerformed

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(alami.isSelected())
        {
        String alamis = tanitv.getText().toString() ;
        double alamit = Double.parseDouble(alamis) ;
         if(alamit < 650){
             
        double alamih = 0 ;
        
        tanitv.setText(alamih+"");        
             
             
         }else{
             
        double alamih = alamit / 100 * 10 ;
        
        tanitv.setText(alamih+"");        
        
             
         }
            
        }else if(tenaga.isSelected())
        {
        String tenagas = tanitv.getText().toString() ;
        double tenagat = Double.parseDouble(tenagas) ;
         if(tenagat < 650){
             
        double tenagah = 0 ;
        
        tanitv.setText(tenagah+"");        
             
             
         }else{
             
        double tenagah = tenagat / 100 * 5 ;
        
        tanitv.setText(tenagah+"");        
        
             
         }
            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamiActionPerformed

    private void tenagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenagaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String galians = galiantv.getText().toString() ;
        double galiant = Double.parseDouble(galians) ;
        
        double galianh = galiant / 100 * 2.5 ;
        
        galiantv.setText(galianh+"");
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String temuans = temuantv.getText().toString() ;
        double temuant = Double.parseDouble(temuans) ;
        
        double temuanh = temuant / 2.5 ;
        
        temuantv.setText(temuanh+"");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void seacrhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seacrhKeyReleased
        // TODO add your handling code here:

        String q = seacrh.getText().toLowerCase() ;
        filter(q) ;

    }//GEN-LAST:event_seacrhKeyReleased

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Biodata Telkom") ;
        MessageFormat footer = new MessageFormat("Page (0,number,integer)") ;

        try{
            tbdata.print(JTable.PrintMode.FIT_WIDTH, header, footer,true, null, true, null) ;

        }catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print", e.getMessage()) ;

        }

    }//GEN-LAST:event_printActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

        emastv.setText("");
        alamattv1.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void tbdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdataMouseClicked
        // TODO add your handling code here:
        int baris = tbdata.getSelectedRow() ;
        if(baris != -1){

            emastv.setText(tbdata.getValueAt(baris, 1).toString()) ;
            if ("10000".equals(tbdata.getValueAt(baris, 2).toString()))
            {
                perak.setSelected(true);
            }
            if ("2.5".equals(tbdata.getValueAt(baris, 3).toString()))
            {
                perak.setSelected(true);
            }
            alamattv1.setText(tbdata.getValueAt(baris, 5).toString()) ;

        }

    }//GEN-LAST:event_tbdataMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectdata();
    }//GEN-LAST:event_refreshActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int baris = tbdata.getSelectedRow() ;

        if("".equals(emastv.getText()) || "".equals(alamattv1.getText()) || "".equals(daftarbarangtv.getText()) ){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);

        }else{
                double totalt = Double.parseDouble(totaltv.getText().toString()) ;
                String SQL = "UPDATE tb_mal SET nama='"+namatvmal.getText()+"',daftar_barang='"+daftarbarangtv.getText()+"',harga="+totalt+",alamat='"+alamattv1.getText()+"' WHERE id_mal='"+tbdata.getValueAt(baris, 0).toString()+"' " ;
                int status = KoneksiDB.execute(SQL) ;
                if(status == 1){

                    JOptionPane.showMessageDialog(this, "Berhasil Ditambahkan","sukses",JOptionPane.INFORMATION_MESSAGE);
                    selectdata();
                }else{

                    JOptionPane.showMessageDialog(this, "Gagal Ditambahkan","gagal",JOptionPane.WARNING_MESSAGE);

                }
            

        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        java.util.Date skrg = new java.util.Date() ;
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy") ;
        if("".equals(alamattv1.getText())|| "".equals(emastv.getText())|| "".equals(daftarbarangtv.getText()) ){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);

        }else{
            
                double totalt = Double.parseDouble(totaltv.getText().toString()) ;
                String SQL = "Insert Into tb_mal(id_mal,nama,daftar_barang,harga,tanggal,alamat)"+"Values("+null+",'"+namatvmal.getText()+"','"+daftarbarangtv.getText()+"',"+totalt+",'"+kal.format(skrg)+"','"+alamattv1.getText()+"') ;" ;
                int status = KoneksiDB.execute(SQL) ;
                if(status == 1){

                    JOptionPane.showMessageDialog(this, "Berhasil Ditambahkan","sukses",JOptionPane.INFORMATION_MESSAGE);
                    selectdata();
                }else{

                    JOptionPane.showMessageDialog(this, "Gagal Ditambahkan","gagal",JOptionPane.WARNING_MESSAGE);

                }


        }

    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        int baris = tbdata.getSelectedRow() ;
        if(baris != -1){
            String SQL = "Delete From tb_mal Where id_mal='"+tbdata.getValueAt(baris, 0).toString()+"'" ;
            int status = KoneksiDB.execute(SQL) ;
            if(status == 1){

                JOptionPane.showMessageDialog(this, "Berhasil Dihapus","sukses",JOptionPane.INFORMATION_MESSAGE);
                selectdata();
            }else{

                JOptionPane.showMessageDialog(this, "Gagal Dihapus","gagal",JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(kambing.isSelected())
        {
        String kambings = ternaktv.getText().toString() ;
        double kambingt = Double.parseDouble(kambings) ;
         if(kambingt < 40){
             
         double tenagah = 0 ;
        
        ternaktv.setText(tenagah+"");        
             
             
         }else if(kambingt > 40 && kambingt <120){
             
         jLabel17.setText("ekor kambing(2th)/ domba");
         double tenagah = 1 ;
        
        ternaktv.setText(tenagah+"");        
             
             
         }else if(kambingt > 120 && kambingt <200){
             
         jLabel17.setText("ekor kambing / domba");
         double tenagah = 2 ;
        
        ternaktv.setText(tenagah+"");        
             
             
         }else if(kambingt > 200){
             
         jLabel17.setText("ekor kambing / domba");
         double tenagah = 1 + kambingt / 100 ;
        
        ternaktv.setText(tenagah+"");        
             
             
         }  
        }else{
            
          String sapis = ternaktv.getText().toString() ;
        double sapit = Double.parseDouble(sapis) ;
         if(sapit < 30){
             
         double tenagah = 0 ;
        
        ternaktv.setText(tenagah+"");        
             
             
         }else if(sapit > 30 && sapit < 39){
             
         double tenagah = 1 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("ekor tabi'/tabi'ah");
             
             
         }else if(sapit > 40 && sapit < 59){
             
         double tenagah = 1 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("ekor musinah");
             
             
         }else if(sapit == 60){
             
         double tenagah = 2 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("ekor tabi'/tabi'ah");
             
             
         }else if(sapit == 70){
             
         double tenagah = 2 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("ekor masing2 tabi' dan musinah");
             
             
         }else if(sapit == 80){
             
         double tenagah = 2 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("musinah");
             
             
         }else if(sapit == 90){
             
         double tenagah = 3 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("ekor tabi'");
             
             
         }  else if(sapit == 100){
             
         double tenagah = 3 ;
        
        ternaktv.setText(tenagah+"");        
         jLabel17.setText("2 ekor tabi/ 1 musinah'");
             
             
         }
            
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String emass = emastv.getText().toString() ;
        double emast = Double.parseDouble(emass) ;
        String alamis = tanitv.getText().toString() ;
        double alamit = Double.parseDouble(alamis) ;
        String galians = galiantv.getText().toString() ;
        double galiant = Double.parseDouble(galians) ;
        String temuans = temuantv.getText().toString() ;
        double temuant = Double.parseDouble(temuans) ;
        String kambings = ternaktv.getText().toString() ;
        double kambingt = Double.parseDouble(kambings) ;
        
        double total = (emast * 538000) + (alamit * 2500) + (galiant * 300000) + temuant + (galiant * 300000) + (kambingt * 3000000) ;
        
        totaltv.setText(total+"");

 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        new Beranda().show();

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamattv1;
    private javax.swing.JRadioButton alami;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea daftarbarangtv;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JRadioButton emas;
    private javax.swing.JTextField emastv;
    private javax.swing.JTextField galiantv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jm;
    private javax.swing.JRadioButton kambing;
    private javax.swing.JTextField namatv5;
    private javax.swing.JTextField namatvmal;
    private javax.swing.JRadioButton perak;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JRadioButton sapi;
    private javax.swing.JButton save;
    private javax.swing.JTextField seacrh;
    private javax.swing.JTextField tanitv;
    private javax.swing.JTable tbdata;
    private javax.swing.JTextField temuantv;
    private javax.swing.JRadioButton tenaga;
    private javax.swing.JTextField ternaktv;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tgl1;
    private javax.swing.JTextField totaltv;
    private javax.swing.JRadioButton uang;
    // End of variables declaration//GEN-END:variables

    public void SetTanggal(){
        java.util.Date skrg = new java.util.Date() ;
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy") ;
        tgl.setText(kal.format(skrg));
    }
    public void SetJam() {
        ActionListener taskPerformer = new ActionListener() {
          @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date() ;
                int nilai_jam = dt.getHours() ;
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
            
                
                String jam = Integer.toString(nilai_jam) ;                
                String menit = Integer.toString(nilai_menit) ;
                String detik = Integer.toString(nilai_detik) ;
                jm.setText("Jam "+jam+" : "+ menit+" : "+detik);
                
                
            }
            
        };
        
            new Timer(100, taskPerformer).start() ;
            
    }
    
    private void selectdata() {
    
        String SQL = "Select * From tb_mal " ;
        ResultSet rs = KoneksiDB.executeQuery(SQL) ;
        
         dtm.getDataVector().removeAllElements();      
        try {
            
            while(rs.next()){
                String id_mal = rs.getString(1) ;
                String nama = rs.getString(2) ;
                String daftar_barang = rs.getString(3) ;
                String harga = rs.getString(4) ;
                String tanggal = rs.getString(5) ;
                String alamat = rs.getString(6) ;
                String data[] = {id_mal,nama,daftar_barang,harga,tanggal,alamat} ;
                dtm.addRow(data);
            }
            
        }catch(SQLException ex){
            
            Logger.getLogger(Mal.class.getName()).log(Level.SEVERE, null, ex) ;
        }
        tbdata.setModel(dtm);
        
    }
    public void filter(String q)
    {
        TableRowSorter<DefaultTableModel> ts=new TableRowSorter<DefaultTableModel>(dtm) ;
        tbdata.setRowSorter(ts);
        
        ts.setRowFilter(RowFilter.regexFilter(q));
        
    }
}
